/**
 * Utilities for working with OpenAPI 3.1 JSON Schemas.
 */

type SchemaObj = Record<string, unknown>;

/**
 * Collapse `anyOf: [{type: X}, {type: "null"}]` → `{type: X, nullable: true}`.
 * Common in OpenAPI 3.1 specs generated by FastAPI/Pydantic.
 */
export function collapseNullable(schema: SchemaObj): SchemaObj {
  const anyOf = schema.anyOf as SchemaObj[] | undefined;
  if (!Array.isArray(anyOf) || anyOf.length !== 2) return schema;

  const nullVariant = anyOf.find((s) => s.type === "null");
  const realVariant = anyOf.find((s) => s.type !== "null");

  if (!nullVariant || !realVariant) return schema;

  // Clone the real variant and add nullable
  const result: SchemaObj = { ...realVariant, nullable: true };

  // Preserve title, description from the outer schema if present
  if (schema.title && !result.title) result.title = schema.title;
  if (schema.description && !result.description) result.description = schema.description;
  if (schema.default !== undefined && result.default === undefined) result.default = schema.default;

  return result;
}

/**
 * Return a human-readable type string for a schema.
 * Examples: "string", "integer", "enum(a|b|c)", "array<string>", "object"
 */
export function getSchemaType(schema: SchemaObj): string {
  // Handle nullable anyOf first
  const collapsed = collapseNullable(schema);
  const nullable = collapsed.nullable ? "?" : "";

  // Enum
  if (Array.isArray(collapsed.enum)) {
    return `enum(${(collapsed.enum as unknown[]).join("|")})${nullable}`;
  }

  const type = collapsed.type as string | undefined;

  if (type === "array") {
    const items = collapsed.items as SchemaObj | undefined;
    if (items) {
      const itemType = getSchemaType(items);
      return `array<${itemType}>${nullable}`;
    }
    return `array${nullable}`;
  }

  if (type === "object") {
    return `object${nullable}`;
  }

  if (type) {
    return `${type}${nullable}`;
  }

  // allOf / oneOf without type
  if (Array.isArray(collapsed.allOf) || Array.isArray(collapsed.oneOf)) {
    return `object${nullable}`;
  }

  return `unknown${nullable}`;
}

/**
 * Check if a field name is in the schema's `required` array.
 */
export function isRequired(name: string, schema: SchemaObj): boolean {
  const required = schema.required as string[] | undefined;
  if (!Array.isArray(required)) return false;
  return required.includes(name);
}

/**
 * Extract enum values from a schema (handling nullable anyOf).
 */
export function extractEnumValues(schema: SchemaObj): unknown[] | undefined {
  const collapsed = collapseNullable(schema);
  if (Array.isArray(collapsed.enum)) {
    return collapsed.enum as unknown[];
  }
  return undefined;
}

/**
 * Flatten allOf/oneOf into a single flat property map.
 * Returns { properties, required } merged from all sub-schemas.
 */
export function flattenProperties(schema: SchemaObj): {
  properties: Record<string, SchemaObj>;
  required: string[];
} {
  const properties: Record<string, SchemaObj> = {};
  const required: string[] = [];

  // Direct properties
  if (schema.properties && typeof schema.properties === "object") {
    Object.assign(properties, schema.properties);
  }
  if (Array.isArray(schema.required)) {
    required.push(...(schema.required as string[]));
  }

  // allOf: merge all sub-schemas
  if (Array.isArray(schema.allOf)) {
    for (const sub of schema.allOf as SchemaObj[]) {
      const flat = flattenProperties(sub);
      Object.assign(properties, flat.properties);
      required.push(...flat.required);
    }
  }

  // oneOf: merge all sub-schemas (best effort for display)
  if (Array.isArray(schema.oneOf)) {
    for (const sub of schema.oneOf as SchemaObj[]) {
      const flat = flattenProperties(sub);
      Object.assign(properties, flat.properties);
      // Don't merge required from oneOf (they're alternatives)
    }
  }

  return { properties, required: [...new Set(required)] };
}
