# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectInvoice(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InvoiceDetection:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectInvoice", llm_response=llm_response, mode="request")
        return typing.cast(types.InvoiceDetection, __result__)

    def ExtractFromPDF(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.EnhancedInvoiceDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFromPDF", llm_response=llm_response, mode="request")
        return typing.cast(types.EnhancedInvoiceDetails, __result__)

    def ExtractInvoiceDetails(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InvoiceDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInvoiceDetails", llm_response=llm_response, mode="request")
        return typing.cast(types.InvoiceDetails, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectInvoice(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InvoiceDetection:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectInvoice", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InvoiceDetection, __result__)

    def ExtractFromPDF(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.EnhancedInvoiceDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractFromPDF", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.EnhancedInvoiceDetails, __result__)

    def ExtractInvoiceDetails(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InvoiceDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInvoiceDetails", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InvoiceDetails, __result__)

    