# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class BankDetails(BaseModel):
    iban: typing.Optional[str] = None
    bic: typing.Optional[str] = None
    account_number: typing.Optional[str] = None
    bank_name: typing.Optional[str] = None

class CompanyAddress(BaseModel):
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    postal_code: typing.Optional[str] = None
    country: typing.Optional[str] = None
    full_address: typing.Optional[str] = None

class EnhancedInvoiceDetails(BaseModel):
    company_name: typing.Optional[str] = None
    invoice_number: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    invoice_date: typing.Optional[str] = None
    due_date: typing.Optional[str] = None
    description: typing.Optional[str] = None
    seller_vat_id: typing.Optional[str] = None
    buyer_name: typing.Optional[str] = None
    buyer_vat_id: typing.Optional[str] = None
    seller_address: typing.Optional["CompanyAddress"] = None
    buyer_address: typing.Optional["CompanyAddress"] = None
    bank_details: typing.Optional["BankDetails"] = None
    line_items: typing.Optional[typing.List["LineItem"]] = None
    tax_amount: typing.Optional[float] = None
    subtotal: typing.Optional[float] = None

class InvoiceDetails(BaseModel):
    company_name: typing.Optional[str] = None
    invoice_number: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    invoice_date: typing.Optional[str] = None
    due_date: typing.Optional[str] = None
    description: typing.Optional[str] = None

class InvoiceDetection(BaseModel):
    status: typing.Optional[types.InvoiceStatus] = None
    confidence: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

class LineItem(BaseModel):
    description: typing.Optional[str] = None
    quantity: typing.Optional[float] = None
    unit_price: typing.Optional[float] = None
    amount: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
