# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BankDetails": types.BankDetails,
    "stream_types.BankDetails": stream_types.BankDetails,

    "types.CompanyAddress": types.CompanyAddress,
    "stream_types.CompanyAddress": stream_types.CompanyAddress,

    "types.EnhancedInvoiceDetails": types.EnhancedInvoiceDetails,
    "stream_types.EnhancedInvoiceDetails": stream_types.EnhancedInvoiceDetails,

    "types.InvoiceDetails": types.InvoiceDetails,
    "stream_types.InvoiceDetails": stream_types.InvoiceDetails,

    "types.InvoiceDetection": types.InvoiceDetection,
    "stream_types.InvoiceDetection": stream_types.InvoiceDetection,

    "types.LineItem": types.LineItem,
    "stream_types.LineItem": stream_types.LineItem,


    "types.InvoiceStatus": types.InvoiceStatus,

}