# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class InvoiceStatus(str, Enum):
    IS_INVOICE = "IS_INVOICE"
    NOT_INVOICE = "NOT_INVOICE"
    MAYBE_INVOICE = "MAYBE_INVOICE"

# #########################################################################
# Generated classes (6)
# #########################################################################

class BankDetails(BaseModel):
    iban: typing.Optional[str] = None
    bic: typing.Optional[str] = None
    account_number: typing.Optional[str] = None
    bank_name: typing.Optional[str] = None

class CompanyAddress(BaseModel):
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    postal_code: typing.Optional[str] = None
    country: typing.Optional[str] = None
    full_address: typing.Optional[str] = None

class EnhancedInvoiceDetails(BaseModel):
    company_name: typing.Optional[str] = None
    invoice_number: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    invoice_date: typing.Optional[str] = None
    due_date: typing.Optional[str] = None
    description: typing.Optional[str] = None
    seller_vat_id: typing.Optional[str] = None
    buyer_name: typing.Optional[str] = None
    buyer_vat_id: typing.Optional[str] = None
    seller_address: typing.Optional["CompanyAddress"] = None
    buyer_address: typing.Optional["CompanyAddress"] = None
    bank_details: typing.Optional["BankDetails"] = None
    line_items: typing.Optional[typing.List["LineItem"]] = None
    tax_amount: typing.Optional[float] = None
    subtotal: typing.Optional[float] = None

class InvoiceDetails(BaseModel):
    company_name: typing.Optional[str] = None
    invoice_number: typing.Optional[str] = None
    amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    invoice_date: typing.Optional[str] = None
    due_date: typing.Optional[str] = None
    description: typing.Optional[str] = None

class InvoiceDetection(BaseModel):
    status: InvoiceStatus
    confidence: float
    reasoning: str

class LineItem(BaseModel):
    description: str
    quantity: typing.Optional[float] = None
    unit_price: typing.Optional[float] = None
    amount: float

# #########################################################################
# Generated type aliases (0)
# #########################################################################
