#!/bin/bash
set -e

# Validate required environment variables
if [ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]; then
    echo "Error: CLAUDE_CODE_OAUTH_TOKEN environment variable is required"
    exit 1
fi

if [ -z "$API_KEY" ]; then
    echo "Error: API_KEY environment variable is required"
    exit 1
fi

MCP_URL="${MCP_BASE_URL:-http://host.docker.internal:3013}"

echo "=== Agent Swarm Worker ==="
echo "Agent ID: ${AGENT_ID:-<not set>}"
echo "MCP Base URL: $MCP_URL"
echo "YOLO Mode: ${WORKER_YOLO:-false}"
echo "Session ID: ${SESSION_ID:-<auto-generated>}"
echo "Working Directory: /workspace"
echo "=========================="

# Create .mcp.json in /workspace (project-level config)
echo "Creating MCP config in /workspace..."
if [ -n "$AGENT_ID" ]; then
    # With AGENT_ID header
    cat > /workspace/.mcp.json << EOF
{
  "mcpServers": {
    "agent-swarm": {
      "type": "http",
      "url": "${MCP_URL}/mcp",
      "headers": {
        "Authorization": "Bearer ${API_KEY}",
        "X-Agent-ID": "${AGENT_ID}"
      }
    }
  }
}
EOF
else
    # Without AGENT_ID header
    cat > /workspace/.mcp.json << EOF
{
  "mcpServers": {
    "agent-swarm": {
      "type": "http",
      "url": "${MCP_URL}/mcp",
      "headers": {
        "Authorization": "Bearer ${API_KEY}"
      }
    }
  }
}
EOF
fi

# Run the worker using compiled binary
echo "Starting worker..."
exec /usr/local/bin/agent-swarm worker "$@"
